name: publish
on: [push]

jobs:
  publish-webworkflow-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build and package with Gradle
        run: make package

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: push to GitHub Package Registry
        run: |
          docker tag com/webworkflow ghcr.io/mekhail-meiring/webworkflow:latest
          docker push ghcr.io/mekhail-meiring/webworkflow:latest

      - name: push to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag com/webworkflow mekhail/webworkflow:latest
          docker push mekhail/webworkflow:latest