name: publish
on: [push]
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
          uses: actions/setup-java@v1
          with:
            java-version: 17

      - name: Build and package with Gradle
          run: make package

      - name: Login to GitHub Container Registry
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish docker container
          run: |
            @echo "Publishing..."
            sudo docker tag com/webworkflow ghcr.io/Mekhail-Meiring/webworkflow:0.0.1-SNAPSHOT
            sudo docker run ghcr.io/Mekhail-Meiring/webworkflow:0.0.1-SNAPSHOT
            sudo docker push ghcr.io/Mekhail-Meiring/webworkflow:0.0.1-SNAPSHOT
            @echo "Done."