name: publish
on: [push]
jobs:
  publish-hello-docker-image:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
  uses: docker/login-action@v1
  with:
  registry: ghcr.io
  username: ${{ github.actor }}
  password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and publish docker container
  run: |
    make package
    @echo "Publishing..."
    sudo docker tag com/webworkflow ghcr.io/Mekhail-Meiring/webworkflow:0.0.1-SNAPSHOT
    sudo docker run ghcr.io/Mekhail-Meiring/webworkflow:0.0.1-SNAPSHOT
    sudo docker push ghcr.io/Mekhail-Meiring/webworkflow:0.0.1-SNAPSHOT
    @echo "Done."