name: publish
on: [push]

jobs:
  publish-webworkflow-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build and package with Gradle
        run: make package

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: push to GitHub Package Registry
        run: |
          docker docker.io/com/webworkflow:latest ghcr.io/mekhail-meiring/webworkflow:latest
          docker push ghcr.io/mekhail-meiring/webworkflow:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: push to Docker Hub
        run: |
          docker tag docker.io/com/webworkflow:latest mekhail/webworkflow:latest
          docker push mekhail/webworkflow:latest

      - name: Get tag name
        uses: olegtarasov/get-tag@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}

      - name: Provision Droplet and deploy container
        run: ioctl compute droplet create "$GIT_TAG_NAME" --image docker-18-04 --size s-1vcpu-1gb --region nyc1 --user-data-file deploy.sh --wait
